- name: Variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10HRS
    TRAINER: Siva
  tasks:
  - name: print the variable
  vars:
    COURSE: DevOps
  ansible.builtin.debug:
    msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}" 