- name: Variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}" 